name: CI

on:
  push:

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npx tsc --noEmit

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
        env:
          BURGER_API_URL: ${{ vars.BURGER_API_URL }}
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      - run: npm run test
      - run: npx playwright install --with-deps
      - run: npm run pl
        env:
          BURGER_API_URL: ${{ vars.BURGER_API_URL }}